on:
  push:
    branches:
      - appsec-aks-demo
    paths:
      - 'lab_3/**'

name: Lab_3_WebApp on AKS

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout
      uses: actions/checkout@v2.1.0
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az group create --name DevOpsBootCampRG --location eastus
                  
    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n DevOpsBootCampRGCR -g DevOpsBootCampRG --location "East US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n DevOpsBootCampRGCR --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n DevOpsBootCampRGCR --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n DevOpsBootCampRGCR --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: devopsbootcamprgcr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
          docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t devopsbootcamprgcr.azurecr.io/node-tm-appsec-demo:${{ github.sha }}
          docker push devopsbootcamprgcr.azurecr.io/node-tm-appsec-demo:${{ github.sha }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az acr repository list --name DevOpsBootCampRGCR --output table
    
    - name: Docker Run
      id: docker-run
      run: |
          docker run -d devopsbootcamprgcr.azurecr.io/node-tm-appsec-demo -p 8080:8080
          docker ps -a
